version: '3'
services:
  ldap:
    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "MyOrg"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"